#!/bin/bash

if [[ $2 != "-V" ]]
then
        command="ypcat hosts"
else
        command="ypcat hosts | grep -v \"v$\""
fi

check_health () {
eval $command | grep --color -i "$search" | sort -k2 | uniq | \

while read line; do
        ping -c 1 -w1 ` echo $line |grep -o '[0-9]*[0-9]\.[0-9]*[0-9]\.[0-9]*[0-9]\.[0-9]*[0-9]' ` > /dev/null
        if [ $? -eq 0 ]
        then
                echo -e "\033[00;32m"[LIVE]"\t\033[0m"$line
        else
                echo -e "\033[00;31m"[DOWN]"\t\033[0m"$line
        fi;
done
}

if [[ $1 == "" ]]
then
        echo -e \tUsage: $0 queryString [-V]
        echo -e "\t-V: Suppress VMs (and entries ending in 'v')"
else
        search=$1
        check_health | column -t
fi;
